### PR TITLE
Permit listening to version messages

### PR DESCRIPTION
**Pull request by dmos62**
Dependant PR: https://github.com/bisq-network/bisq/pull/4081

Commit message for commit titled "Add listener for when a VersionMessage is received" explains the purpose of the PR in general:

```
Since Bisq requires nodes with specific configuration (as reflected in
their version messages), we also want to handle misconfigured nodes,
especially in cases where the user expects that node to be used. To get
access to all received version messages, a new listener is introduced.
Existing listeners are not sufficient, because in some cases BitcoinJ
will kill the Peer (connection to a node) before any of them are
triggered. This listener will always be triggered when a VersionMessage
is received.
```

In total, this PR introduces a bugfix (Permit alerts during handshake, see https://github.com/bisq-network/bisq/issues/4080), a compilation breaking fix (Fix javadoc compilation on JDK 11), a new listener (Add listener for when a VersionMessage is received) and bumps the version number (`0.14.7.bisq.1-SNAPSHOT` -> `0.14.7.bisq.2-SNAPSHOT`).

It should be noted that there is a failing test (not resulting from this PR): `ChannelConnectionTest.testChannelResume:459->roundTripClientWallet:551 » IllegalState`.

### CODE REVIEW

**Review by chimp1984 — APPROVED** [review]
utACK
It looks good to me. 
@oscarguindzberg Could you review it and if ACKed request from the maintainers to merge it into a new branch? We have an open PR in Bisq which depends on that PR.

**Comment by oscarguindzberg** [comment]
We are moving to bitcoinj 0.15. I expect to create the PR this week. 
It might be worth testing the issue described in https://github.com/bisq-network/bisq/pull/4081 and https://github.com/bisq-network/bisq/issues/4080 again once the PR is merged.
For sure bitcoinj 0.15 will bump bitcoinj client version to 70012.

**Comment by oscarguindzberg** [comment]
On top of that, I would avoid doing "code polishing" (e.g. removing useless spaces at the end of lines) on our bitcoinj fork. Those changes could be a PR to bitcoinj upstream. The more we change our bitcoinj fork, the hardest it is to merge changes from upstream.

**Comment by dmos62** [comment]
> On top of that, I would avoid doing "code polishing" (e.g. removing useless spaces at the end of lines) on our bitcoinj fork. Those changes could be a PR to bitcoinj upstream. The more we change our bitcoinj fork, the hardest it is to merge changes from upstream.

Sorry about those. My editor trims whitespace automatically when saving. Normally I wouldn't have included those changes, but I missed them that time.

**Comment by dmos62** [comment]
Oh, this PR is merging into the wrong branch. I'll resubmit.

**Pull request closed without merging**
